name: 好记性韦恩
url: http://example.org
description: 春眠不觉晓，处处闻啼鸟，夜来风雨声，花落知多少。

permalink: /:year/:month/:day/:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

# Author
author:
  name: 石少华
  desc: Hello nice to meet you
  email: shi.sh@foxmail.com
  selfie: /images/avatar.jpg

# social
social:
  email: true
  behance:
  bitbucket:
  dribbble:
  facebook: Test
  flickr:
  github: kssim
  google_plus:
  instagram: https://www.instagram.com/shaohua.shi/
  keybase:
  linkedin:  
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:
  steam:
  tumblr:
  gitlab:
  twitter: Test
  vimeo:
  wordpress:
  youtube:
  default_txt: "Follow On"
