name: 好记性韦恩
url: http://example.org
description: 

permalink: /:year/:month/:day/:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

# Author
author:
  name: 石少华
  desc: Hello nice to meet you
  email: shi.sh@foxmail.com
  selfie: /images/avatar.jpg

# social
social:
  email: true
  weibo: 1294004943
  douban: omega7
  dribbble:
  facebook: Test
  flickr:
  github: shshi
  google_plus:
  instagram: shaohua.shi
  keybase:
  linkedin:  
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:
  steam:
  tumblr:
  gitlab:
  twitter: Test
  vimeo:
  wordpress:
  youtube:
  default_txt: "Follow On"
