name: 石少华
url: http://example.org
#description: 欢迎来到韦恩的博客

permalink: /:year/:month/:day/:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

# Author
author:
  name: 石少华
  desc: Hello nice to meet you
  email: shi.sh@foxmail.com
  selfie: /images/avatar.jpg

# social (douban: omega7)
social:
  email: true
  weibo: 1294004943
  douban:
  dribbble:
  facebook:
  flickr:
  github: shshi
  google_plus:
  instagram: shaohua.shi
  keybase:
  linkedin:
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:
  steam:
  tumblr:
  gitlab:
  twitter:
  vimeo:
  wordpress:
  youtube:
  default_txt: "Follow On"
